# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-12 17:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0009_remove_channel_subchannels'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestLog',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('recipient',
                 models.CharField(
                     max_length=300,
                     verbose_name='Recipient email')),
                ('context',
                 django.contrib.postgres.fields.jsonb.JSONField(
                     blank=True,
                     null=True,
                     verbose_name='Context')),
                ('campaign',
                 models.IntegerField(
                     blank=True,
                     null=True,
                     verbose_name='Campaign')),
                ('channel',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='digestlog_channel',
                     to='channels.Channel')),
            ],
            options={
                'abstract': False,
            },
            bases=(
                ovp.apps.channels.models.mixins.ChannelCreatorMixin,
                models.Model),
        ),
    ]
