# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-12 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestlog',
            name='trigger_date',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
