# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-02 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_remove_channel_subchannels'),
        ('digest', '0002_digestlog_trigger_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestLogContent',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('content_type',
                 models.IntegerField(
                     choices=[
                         (1,
                          'Project')],
                     verbose_name='Content type')),
                ('content_id',
                 models.IntegerField(
                     verbose_name='Content id')),
                ('channel',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='digestlogcontent_channel',
                     to='channels.Channel')),
                ('digest_log',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='digest.DigestLog')),
            ],
            options={
                'abstract': False,
            },
            bases=(
                ovp.apps.channels.models.mixins.ChannelCreatorMixin,
                models.Model),
        ),
    ]
