# Generated by Django 2.2.11 on 2020-04-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0004_digestlog_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestlog',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='digestlog_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='digestlogcontent',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='digestlogcontent_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='digestlogcontent',
            name='digest_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='digest.DigestLog'),
        ),
    ]
