# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-27 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20190420_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
