# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-27 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_transaction_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='used_token',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
