# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-28 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_transaction_backend_transaction_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True),
        ),
    ]
