# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-29 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_channel_subchannels'),
        ('donations', '0008_auto_20190428_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='channel',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscription_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='channel',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transaction_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
    ]
