# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-29 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_auto_20190429_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='used_token',
        ),
    ]
