# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-17 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_remove_transaction_used_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='backend_plan_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='backend_subscription_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='backend_transaction_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='backend_transaction_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
