# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-17 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_auto_20191017_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='anonymous',
            field=models.BooleanField(
                default=False,
                verbose_name='Anonymous subscription'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='anonymous',
            field=models.BooleanField(
                default=False,
                verbose_name='Anonymous subscription'),
        ),
    ]
