# Generated by Django 2.2.11 on 2020-04-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_auto_20191128_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscription_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_channel', to='channels.Channel'),
        ),
    ]
