# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 19:14
from __future__ import unicode_literals

from django.db import migrations

def forward_func(apps, schema_editor):
    Channel = apps.get_model('channels', 'Channel')
    ChannelSetting = apps.get_model('channels', 'ChannelSetting')
    channel = Channel.objects.get(slug="icn")
    ChannelSetting.objects.create(key="DISABLE_EMAIL", value="emailVerification", channel=channel)
    return True

def rewind_func(apps, schema_editor):
    return True

class Migration(migrations.Migration):

    dependencies = [
        ('icn', '0002_remove_skills_and_causes'),
    ]

    operations = [
        migrations.RunPython(forward_func, rewind_func)
    ]
