# Generated by Django 2.2.11 on 2020-04-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20180807_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='itemdocument',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemdocument_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='itemdocument',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uploads.UploadedDocument', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemimage_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uploads.UploadedImage', verbose_name='image'),
        ),
    ]
