# User-defined substitutions:
#   _CLOUDSDK_COMPUTE_ZONE
#   _CLOUDSDK_CONTAINER_CLUSTER
#   _GITHUB_USERNAME
#   _KMS_KEY
#   _KMS_KEYRING

steps:
  # Build the pipeline container image.
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/${PROJECT_ID}/atados-ovp:${COMMIT_SHA}
      - --cache=true
      - --cache-ttl=168h
