version: '3'

services:
  es:
    container_name: ovp-es2
    image: elasticsearch:2.4.6-alpine
  rabbitmq:
    container_name: ovp-rabbitmq
    image: rabbitmq:3.7.8
  db:
    container_name: ovp-db
    image: postgres:9.6
    volumes:
      - ovp-db-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=ovp'
      - 'POSTGRES_USER=atd'
      - 'POSTGRES_PASSWORD=atd'
  api:
    container_name: ovp-api
    build: .
    environment:
      - 'DATABASE_URL=postgres://atd:atd@db:5432/ovp'
      - 'DJANGO_SECRET_KEY=abc'
      - 'RABBITMQ_URL=amqp://rabbitmq'
      - 'HS_SEARCH_ENDPOINT=ovp-es2:9200'
    command: make docker-entrypoint
    volumes:
      - ./api:/www/api
    ports:
      - '8000:8000'
    depends_on:
      - db
volumes:
  ovp-db-data:
