# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_auto_20170828_1403'),
        ('uploads', '0006_auto_20170613_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='uploadedimage_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
    ]
