# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins
import ovp.apps.uploads.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0007_channelsetting'),
        ('uploads', '0008_auto_20170921_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=ovp.apps.uploads.models.DocumentName())),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(blank=True, default=None, max_length=36, verbose_name='UUID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Name')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadeddocument_channel', to='channels.Channel')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uploaded document',
                'verbose_name_plural': 'uploaded documents',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
    ]
