# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0010_auto_20180705_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='absolute',
            field=models.BooleanField(default=False, verbose_name='Absolute'),
        ),
    ]
