# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-11 13:38
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms
import ovp.apps.uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0017_merge_20190327_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_large',
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default=None,
                force_format=None,
                keep_meta=False,
                max_length=300,
                null=True,
                quality=60,
                size=[
                    1260,
                    936],
                upload_to=ovp.apps.uploads.models.ImageName('-large')),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_medium',
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default=None,
                force_format=None,
                keep_meta=False,
                max_length=300,
                null=True,
                quality=60,
                size=[
                    420,
                    312],
                upload_to=ovp.apps.uploads.models.ImageName('-medium')),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_small',
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default=None,
                force_format=None,
                keep_meta=False,
                max_length=300,
                null=True,
                quality=60,
                size=[
                    350,
                    260],
                upload_to=ovp.apps.uploads.models.ImageName('-small')),
        ),
    ]
