# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-01 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0019_auto_20190418_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageGalery',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='category',
        ),
    ]
