# Generated by Django 2.2.11 on 2020-04-22 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import ovp.apps.uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0022_auto_20191121_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploadeddocument_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploadedimage_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_large',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, max_length=300, null=True, quality=90, size=[1260, 936], upload_to=ovp.apps.uploads.models.ImageName('-large')),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_medium',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, max_length=300, null=True, quality=90, size=[420, 312], upload_to=ovp.apps.uploads.models.ImageName('-medium')),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_small',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, max_length=300, null=True, quality=90, size=[350, 260], upload_to=ovp.apps.uploads.models.ImageName('-small')),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
