# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 01:14
from __future__ import unicode_literals

from django.db import migrations

# This migration is deprecated and is now executed as a signal


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cause_skill'),
    ]

    operations = [
    ]
