# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20170714_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('content',
                 models.TextField(
                     max_length=3000,
                     verbose_name='content')),
                ('created_date',
                 models.DateTimeField(
                     auto_now_add=True,
                     verbose_name='Created date')),
                ('reply_to',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     to='core.Commentary',
                     verbose_name='reply')),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='user')),
            ],
        ),
    ]
