# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_auto_20170828_1403'),
        ('core', '0014_auto_20170825_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelContact',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('email',
                 models.EmailField(
                     max_length=200,
                     verbose_name='Email')),
                ('channel',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='channelcontact_channel',
                     to='channels.Channel')),
            ],
            options={
                'abstract': False,
            },
            bases=(
                ovp.apps.channels.models.mixins.ChannelCreatorMixin,
                models.Model),
        ),
    ]
