# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_auto_20170828_1403'),
        ('core', '0015_channelcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresscomponent',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='addresscomponent_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresscomponenttype',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='addresscomponenttype_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googleaddress',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='googleaddress_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googleregion',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='googleregion_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simpleaddress',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='simpleaddress_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
    ]
