# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170828_1420'),
        ('core', '0014_commentary'),
    ]

    operations = [
    ]
