# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_channelsetting'),
        ('core', '0017_merge_20170912_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleaddress',
            name='channel',
        ),
        migrations.AddField(
            model_name='commentary',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='commentary_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SimpleAddress',
        ),
    ]
