# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:02
from __future__ import unicode_literals

from django.db import migrations
from ovp.apps.core.helpers import generate_slug


def foward_func(apps, schema_editor):
    Skill = apps.get_model('core', 'Skill')
    Cause = apps.get_model('core', 'Cause')
    for skill in Skill.objects.all():
        skill.slug = generate_slug(Skill, skill.name, skill.channel.slug)
        skill.save()
    for cause in Cause.objects.all():
        cause.slug = generate_slug(Cause, cause.name, cause.channel.slug)
        cause.save()
    return True


def rewind_func(apps, schema_editor):
    Skill = apps.get_model('core', 'Skill')
    Cause = apps.get_model('core', 'Cause')
    for skill in Skill.objects.all():
        skill.slug = None
    for cause in Cause.objects.all():
        cause.slug = None
    return True


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20171005_1851'),
    ]

    operations = [
        migrations.RunPython(foward_func, rewind_func)
    ]
