# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20171005_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='City'),
        ),
    ]
