# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_lead_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleaddress',
            options={
                'verbose_name': 'google address',
                'verbose_name_plural': 'google addresses'},
        ),
        migrations.AlterField(
            model_name='googleaddress',
            name='address_line',
            field=models.CharField(
                blank=True,
                max_length=400,
                null=True,
                verbose_name='Address line'),
        ),
        migrations.AlterField(
            model_name='googleaddress',
            name='city_state',
            field=models.CharField(
                blank=True,
                max_length=400,
                null=True,
                verbose_name='City/state'),
        ),
        migrations.AlterField(
            model_name='googleaddress',
            name='lat',
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='googleaddress',
            name='lng',
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='googleaddress',
            name='typed_address',
            field=models.CharField(
                blank=True,
                max_length=400,
                null=True,
                verbose_name='Typed address'),
        ),
        migrations.AlterField(
            model_name='googleaddress',
            name='typed_address2',
            field=models.CharField(
                blank=True,
                max_length=400,
                null=True,
                verbose_name='Typed address 2'),
        ),
    ]
