# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_channelsetting'),
        ('core', '0024_availability_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=300, null=True, verbose_name='Logradouro')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('neighbourhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('supplement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simpleaddress_channel', to='channels.Channel')),
            ],
            options={
                'abstract': False,
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
    ]
