# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-12 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_lead_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='employee_number',
            field=models.IntegerField(default=0),
        ),
    ]
