# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-17 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_lead_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('company',
                     'Company'),
                    ('nonprofit',
                     'Nonprofit')],
                default='',
                max_length=10,
                null=True),
        ),
    ]
