# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-17 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20180717_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='employee_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
