# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_remove_channel_subchannels'),
        ('core', '0029_auto_20180717_1458'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cause',
            unique_together=set([('slug', 'channel')]),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([('slug', 'channel')]),
        ),
    ]
