# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-25 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190612_1734'),
        ('projects', '0086_remove_project_commentaries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='user',
        ),
        migrations.DeleteModel(
            name='Commentary',
        ),
    ]
