# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-26 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(
                auto_now=True,
                verbose_name='Modified date'),
        ),
    ]
