# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-01 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_post_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
