# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-07 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_flair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flair',
            name='value',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='value'),
        ),
    ]
