# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-01 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20190807_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='employee_number',
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name='Employee number'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('company',
                     'Company'),
                    ('nonprofit',
                     'Nonprofit')],
                default='',
                max_length=10,
                null=True,
                verbose_name='Type'),
        ),
    ]
