# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20191001_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('company',
                     'Company'),
                    ('nonprofit',
                     'Nonprofit')],
                default='',
                max_length=10,
                null=True),
        ),
    ]
