# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-11 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='question')),
                ('answer', models.CharField(default='', max_length=3000, verbose_name='answer')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='faq.Category', verbose_name='category')),
            ],
        ),
    ]
