# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(
                default='',
                max_length=3000,
                verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to='faq.Category',
                verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(
                max_length=100,
                verbose_name='Pergunta'),
        ),
    ]
