# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20170425_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to='faq.Category',
                verbose_name='Categoria'),
        ),
    ]
