# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_auto_20170828_1403'),
        ('faq', '0003_auto_20170425_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=100,
                     verbose_name='Category name')),
                ('channel',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='faqcategory_channel',
                     to='channels.Channel')),
            ],
            options={
                'abstract': False,
            },
            bases=(
                ovp.apps.channels.models.mixins.ChannelCreatorMixin,
                models.Model),
        ),
        migrations.AddField(
            model_name='faq',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='faq_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to='faq.FaqCategory',
                verbose_name='Categoria'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
