# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 12:51
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20170828_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(
                default='',
                max_length=3000,
                verbose_name='Resposta'),
        ),
    ]
