# Generated by Django 2.2.11 on 2020-04-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0007_faq_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='faq.FaqCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='faq_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='faqcategory_channel', to='channels.Channel'),
        ),
    ]
