version: 2.1

executors:
  build-test-and-release:
    docker:
      - image: circleci/python:3.7
        environment:
          DATABASE_URL: postgres://root:@localhost:5432/circle-test
          DJANGO_SECRET_KEY: '123'

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test

      - image: circleci/rabbitmq

    working_directory: ~/repo

jobs:
  build:
    executor: build-test-and-release
    steps:
      - checkout

      - run:
          name: Pull Submodules
          command: git submodule init && git submodule update --remote

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt --user

      - run:
          name: Collect static
          command: python api/manage.py collectstatic
      
      # Executando testes por Apps
      - run:
          name: Run core tests
          command: python api/manage.py test ovp.apps.core ovp.apps.uploads ovp.apps.users ovp.apps.organizations ovp.apps.projects ovp.apps.search ovp.apps.faq ovp.apps.channels ovp.apps.catalogue ovp.apps.ratings ovp.apps.gallery ovp.apps.digest

      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  build-test-and-release:
    jobs:
      - build
