# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_auto_20170613_1424'),
        ('projects', '0039_auto_20170728_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     max_length=150,
                     verbose_name='name')),
                ('slug',
                 models.SlugField(
                     blank=True,
                     max_length=100,
                     null=True,
                     unique=True)),
                ('description',
                 models.CharField(
                     blank=True,
                     max_length=3000,
                     null=True,
                     verbose_name='description')),
                ('highlighted',
                 models.BooleanField(
                     default=False,
                     verbose_name='Highlighted')),
                ('image',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='category_image',
                     to='uploads.UploadedImage',
                     verbose_name='image')),
            ],
        ),
    ]
