# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20170728_1903'),
        ('projects', '0039_auto_20170728_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='channels',
            field=models.ManyToManyField(
                related_name='channels',
                to='channels.Channel'),
        ),
    ]
