# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_merge_20170803_2007'),
        ('projects', '0040_project_channels'),
    ]

    operations = [
    ]
