# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0044_merge_20170803_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('content',
                 models.TextField(
                     max_length=3000,
                     verbose_name='content')),
                ('reply_to',
                 models.IntegerField(
                     default=0)),
                ('created_date',
                 models.DateTimeField(
                     auto_now_add=True,
                     verbose_name='Created date')),
                ('project',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='projects.Project',
                     verbose_name='project')),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='user')),
            ],
        ),
    ]
