# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='projects.Project',
                verbose_name='project'),
        ),
    ]
