# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 20:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0046_auto_20170825_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=3000, verbose_name='content')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Commentary', verbose_name='reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='project',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AddField(
            model_name='project',
            name='commentaries',
            field=models.ManyToManyField(to='projects.Commentary', verbose_name='commentaries'),
        ),
    ]
