# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20170728_1903'),
        ('projects', '0046_auto_20170808_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='channels',
        ),
        migrations.AddField(
            model_name='project',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='project_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
    ]
