# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20170728_1903'),
        ('projects', '0047_auto_20170822_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='apply_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='category_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='job_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdate',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='jobdate_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerrole',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='volunteerrole_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='work_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
    ]
