# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20170831_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='reply_to',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='projects.Commentary',
                verbose_name='reply'),
        ),
    ]
