# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_auto_20170831_2049'),
        ('core', '0014_commentary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='commentaries',
            field=models.ManyToManyField(to='core.Commentary', verbose_name='commentaries'),
        ),
        migrations.DeleteModel(
            name='Commentary',
        ),
    ]
