# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_auto_20170828_1403'),
        ('projects', '0048_auto_20170822_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('slug', 'channel')]),
        ),
    ]
