# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_auto_20170818_1647'),
        ('projects', '0049_auto_20170904_1652'),
        ('projects', '0049_auto_20170828_2111'),
    ]

    operations = [
    ]
