# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0007_channelsetting'),
        ('projects', '0050_merge_20170912_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProject',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('channel',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='favoriteproject_channel',
                     to='channels.Channel')),
                ('project',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='projects.Project')),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(
                ovp.apps.channels.models.mixins.ChannelCreatorMixin,
                models.Model),
        ),
    ]
