# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_auto_20170921_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbookmark',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
