# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_auto_20171001_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(
                to='projects.Category',
                verbose_name='categories'),
        ),
    ]
