# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_auto_20171006_1419'),
        ('projects', '0056_auto_20171005_1509'),
    ]

    operations = [
    ]
