# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 12:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_merge_20171009_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='details',
            field=ckeditor.fields.RichTextField(
                max_length=3000,
                verbose_name='Details'),
        ),
    ]
