# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_auto_20180504_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.GoogleAddress',
                verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.TextField(
                max_length=3000,
                verbose_name='Details'),
        ),
    ]
