# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-22 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_project_item'),
        ('projects', '0062_auto_20180712_0822'),
    ]

    operations = [
    ]
