# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_auto_20181105_1056'),
        ('projects', '0066_auto_20181023_1436'),
    ]

    operations = [
    ]
