# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 02:36
from __future__ import unicode_literals

from django.db import migrations


def foward_func(apps, schema_editor):
    Apply = apps.get_model('projects', 'Apply')
    Apply.objects.filter(canceled=True).update(status="unapplied")
    return True


def rewind_func(apps, schema_editor):
    return True


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_auto_20181106_1540'),
    ]

    operations = [
        migrations.RunPython(foward_func, rewind_func)
    ]
