# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_auto_20181113_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='canceled',
        ),
    ]
