# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-04 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0076_project_partnership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='benefited_people',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
