# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-13 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0016_auto_20190121_1733'),
        ('projects', '0076_project_galleries'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(
                to='uploads.UploadedDocument',
                verbose_name='documents'),
        ),
    ]
