# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-13 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0078_apply_document'),
        ('projects', '0078_project_chat_enabled'),
    ]

    operations = [
    ]
