# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0078_project_testimony'),
        ('projects', '0079_merge_20190312_2131'),
    ]

    operations = [
    ]
