# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-22 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0079_merge_20190312_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='canceled',
            field=models.BooleanField(
                default=False,
                verbose_name='Canceled'),
        ),
        migrations.AddField(
            model_name='project',
            name='canceled_date',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Closed date'),
        ),
    ]
