# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-22 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_auto_20190322_0655'),
        ('projects', '0080_merge_20190316_2247'),
    ]

    operations = [
    ]
