# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-27 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0075_auto_20181231_1116'),
        ('projects', '0081_merge_20190322_0700'),
    ]

    operations = [
    ]
