# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-17 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0084_auto_20190418_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='canceled_date',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Canceled date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='organizations.Organization',
                verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(
                blank=True,
                max_length=100,
                null=True,
                unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(
                []),
        ),
    ]
