# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-01 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0087_project_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='posts',
            field=models.ManyToManyField(to='core.Post', verbose_name='posts'),
        ),
    ]
