# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-02 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0090_auto_20190705_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='message',
            field=models.TextField(
                blank=True,
                max_length=3000,
                null=True,
                verbose_name='message'),
        ),
    ]
