# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0093_auto_20191001_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='benefited_people',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
