# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-05 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0094_auto_20191121_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('unapplied', 'Canceled'), ('confirmed-volunteer', 'Confirmed Volunteer'), ('not-volunteer', 'Not a Volunteer'), ('unapplied-by-deactivation', 'Unapplied by deactivation')], default='applied', max_length=30, verbose_name='status'),
        ),
    ]
