# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_auto_20170728_1924'),
        ('organizations', '0025_auto_20170728_1923'),
    ]

    operations = [
    ]
