# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_auto_20170828_1403'),
        ('organizations', '0026_merge_20170803_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='organization_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationinvite',
            name='channel',
            field=models.ForeignKey(
                default='',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='organizationinvite_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
    ]
