# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_channelsetting'),
        ('organizations', '0027_auto_20170828_1825'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set([('slug', 'channel')]),
        ),
    ]
