# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0029_organizationbookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationbookmark',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bookmarks',
                to='organizations.Organization'),
        ),
    ]
