# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 19:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0031_auto_20171006_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='organizations',
                to=settings.AUTH_USER_MODEL,
                verbose_name='owner'),
        ),
    ]
