# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0032_auto_20171006_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
