# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 12:41
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0033_organization_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='details',
            field=ckeditor.fields.RichTextField(
                blank=True,
                default=None,
                max_length=3000,
                null=True,
                verbose_name='Details'),
        ),
    ]
