# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0035_auto_20171121_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(
                blank=True,
                max_length=320,
                null=True,
                verbose_name='Short description'),
        ),
    ]
