# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0036_auto_20171212_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='document',
            field=models.CharField(
                blank=True,
                default=None,
                max_length=18,
                null=True,
                verbose_name='document'),
        ),
    ]
