# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import ovp.apps.organizations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0037_organization_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='document',
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                unique=True,
                validators=[
                    ovp.apps.organizations.validators.validate_CNPJ],
                verbose_name='document'),
        ),
    ]
