# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0039_auto_20180705_1218'),
        ('organizations', '0040_auto_20180712_1347'),
    ]

    operations = [
    ]
