# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0042_auto_20180816_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvite',
            name='created_date',
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
                verbose_name='Joined date'),
        ),
        migrations.AddField(
            model_name='organizationinvite',
            name='joined_date',
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name='Joined date'),
        ),
        migrations.AddField(
            model_name='organizationinvite',
            name='revoked_date',
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name='Modified date'),
        ),
    ]
