# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0044_auto_20180921_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.OneToOneField(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.SimpleAddress',
                verbose_name='address'),
        ),
    ]
