# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0045_auto_20181023_1436'),
        ('organizations', '0045_auto_20181022_1431'),
    ]

    operations = [
    ]
