# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-05 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0047_auto_20181106_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.OneToOneField(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.SimpleAddress',
                verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(
                max_length=300,
                verbose_name='Name'),
        ),
    ]
