# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-10 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0048_organization_categories'),
        ('organizations', '0048_auto_20181204_2323'),
    ]

    operations = [
    ]
