# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-04 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0050_auto_20190121_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='benefited_people',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
