# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-27 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0051_auto_20190204_1237'),
        ('organizations', '0050_auto_20181231_1116'),
    ]

    operations = [
    ]
