# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-17 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20190314_1505'),
        ('organizations', '0055_auto_20190617_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='galleries',
            field=models.ManyToManyField(
                blank=True,
                related_name='galleries',
                to='gallery.Gallery',
                verbose_name='galleries'),
        ),
    ]
