# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-07 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0056_organization_galleries'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='instagram_user',
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name='Instagram'),
        ),
    ]
