# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-17 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0055_organization_allow_donations'),
        ('organizations', '0059_auto_20191001_1712'),
    ]

    operations = [
    ]
