# Generated by Django 2.2.11 on 2020-04-22 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0060_merge_20191017_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.GoogleAddress', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uploads.UploadedImage', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uploads.UploadedImage', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='organizationbookmark',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organizationbookmark_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='organizationbookmark',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookmarks', to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organizationinvite_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='invitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='has_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='invited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='been_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Organization'),
        ),
    ]
