# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.CharField(
                default='default',
                max_length=100,
                verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
