# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20170728_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelContact',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('email',
                 models.EmailField(
                     max_length=200,
                     verbose_name='Email')),
                ('channel',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='channels.Channel')),
            ],
        ),
    ]
