# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_channelcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelcontact',
            name='channel',
        ),
        migrations.DeleteModel(
            name='ChannelContact',
        ),
    ]
