# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_auto_20170828_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSetting',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('key',
                 models.CharField(
                     max_length=100,
                     verbose_name='Key')),
                ('value',
                 models.TextField(
                     verbose_name='Value')),
                ('channel',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='channelsetting_channel',
                     to='channels.Channel')),
            ],
            options={
                'abstract': False,
            },
            bases=(
                ovp.apps.channels.models.mixins.ChannelCreatorMixin,
                models.Model),
        ),
    ]
