# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-31 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_channelsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='subchannels',
            field=models.ManyToManyField(
                to='channels.Channel',
                verbose_name='subchannel'),
        ),
    ]
