# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-12 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_channel_subchannels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='subchannels',
        ),
    ]
