# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_quantitative', models.FloatField(null=True, verbose_name='quantitative value')),
                ('value_qualitative', models.TextField(blank=True, null=True, verbose_name='qualitative value')),
            ],
        ),
        migrations.CreateModel(
            name='RatingParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.IntegerField(choices=[(1, 'Qualitative'), (2, 'Quantitative')], verbose_name='Parameter type')),
            ],
        ),
        migrations.AddField(
            model_name='ratinganswer',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.RatingParameter'),
        ),
        migrations.AddField(
            model_name='ratinganswer',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Rating'),
        ),
    ]
