# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20181017_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True),
        ),
        migrations.AddField(
            model_name='ratingrequest',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True),
        ),
    ]
