# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_auto_20181017_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingrequest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
