# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_channelsetting'),
        ('ratings', '0006_ratingrequest_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='channel',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rating_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratinganswer',
            name='channel',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ratinganswer_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratingparameter',
            name='channel',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ratingparameter_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratingrequest',
            name='channel',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ratingrequest_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
    ]
