# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_auto_20181023_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingparameter',
            name='name',
            field=models.CharField(
                max_length=100,
                unique=True,
                verbose_name='Name'),
        ),
    ]
