# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_auto_20181029_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingparameter',
            old_name='name',
            new_name='slug',
        ),
    ]
