# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_auto_20181029_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinganswer',
            name='rating',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='answers',
                to='ratings.Rating'),
        ),
        migrations.AlterField(
            model_name='ratingparameter',
            name='type',
            field=models.IntegerField(
                choices=[
                    (1,
                     'Qualitative'),
                    (2,
                     'Quantitative'),
                    (3,
                     'Boolean')],
                verbose_name='Parameter type'),
        ),
    ]
