# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-06 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ratings', '0011_ratingrequest_deleted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingrequest',
            name='initiator_id',
            field=models.PositiveIntegerField(
                default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratingrequest',
            name='initiator_type',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rating_requests_as_initiator',
                to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratingrequest',
            name='content_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rating_requests_as_rated',
                to='contenttypes.ContentType'),
        ),
    ]
