# Generated by Django 2.2.11 on 2020-04-22 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_auto_20181206_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rating_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratings_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ratings.RatingRequest'),
        ),
        migrations.AlterField(
            model_name='ratinganswer',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratinganswer_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='ratinganswer',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ratings.RatingParameter'),
        ),
        migrations.AlterField(
            model_name='ratinganswer',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='ratings.Rating'),
        ),
        migrations.AlterField(
            model_name='ratingparameter',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratingparameter_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='ratingrequest',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratingrequest_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='ratingrequest',
            name='requested_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rating_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
