# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20170728_1903'),
        ('users', '0034_user_exceeded_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channels',
            field=models.ManyToManyField(
                related_name='user_channels',
                to='channels.Channel'),
        ),
    ]
