# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_user_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='channels',
        ),
    ]
