# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_user_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=190, verbose_name='Email'),
        ),
    ]
