# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20170728_1903'),
        ('users', '0038_auto_20170810_1756'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('email', 'channel')]),
        ),
    ]
