# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20170728_1903'),
        ('users', '0039_auto_20170810_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordhistory',
            name='channel',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='passwordhistory_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordrecoverytoken',
            name='channel',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='passwordrecoverytoken_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='channel',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='userprofile_channel',
                to='channels.Channel'),
            preserve_default=False,
        ),
    ]
