# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_auto_20170828_1403'),
        ('users', '0040_auto_20170816_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('slug', 'channel'), ('email', 'channel')]),
        ),
    ]
