# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20170828_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='exceeded_login_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_attempt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_attempts',
        ),
    ]
