# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20171024_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed_to_newsletter',
            field=models.BooleanField(
                default=True,
                verbose_name='Subscribed to newsletter'),
        ),
    ]
