# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20171204_1550'),
        ('users', '0043_user_is_subscribed_to_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.OneToOneField(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.GoogleAddress',
                verbose_name='address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hidden_address',
            field=models.BooleanField(
                default=False,
                verbose_name='Hidden address'),
        ),
    ]
