# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20171204_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='details',
            field=models.TextField(
                blank=True,
                max_length=160,
                null=True,
                verbose_name='Details'),
        ),
    ]
