# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_remove_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
