# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_user_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_login',
        ),
    ]
