# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-07 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20180807_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(
                choices=[
                    ('male',
                     'Male'),
                    ('female',
                     'Female'),
                    ('unspecified',
                     'Unspecified')],
                default='unspecified',
                max_length=20,
                verbose_name='Gender'),
        ),
    ]
