# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20180807_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone2',
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name='Phone 2'),
        ),
    ]
