# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-05 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20190402_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name='Document'),
        ),
    ]
