# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0007_channelsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_channel', to='channels.Channel')),
            ],
            options={
                'abstract': False,
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Catalogue')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_channel', to='channels.Channel')),
            ],
            options={
                'abstract': False,
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SectionFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectionfilter_channel', to='channels.Channel')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Section')),
            ],
            options={
                'abstract': False,
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
    ]
