# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='slug',
            field=models.SlugField(
                default='',
                max_length=100,
                verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(
                max_length=100,
                verbose_name='Slug'),
        ),
    ]
