# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20170925_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionfilter',
            name='type',
            field=models.CharField(
                choices=[
                    ('CATEGORY',
                     'Category')],
                default='',
                max_length=30,
                verbose_name='Filter type'),
            preserve_default=False,
        ),
    ]
