# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20170925_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionfilter',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
