# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_merge_20170803_2020'),
        ('catalogue', '0007_auto_20170926_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfilter',
            name='categories',
            field=models.ManyToManyField(to='projects.Category'),
        ),
    ]
