# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_channelsetting'),
        ('catalogue', '0010_section_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogue',
            options={'verbose_name': 'catalogue', 'verbose_name_plural': 'catalogues'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'catalogue', 'verbose_name_plural': 'catalogues'},
        ),
        migrations.AlterUniqueTogether(
            name='catalogue',
            unique_together=set([('slug', 'channel')]),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('slug', 'catalogue')]),
        ),
    ]
