# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_datedeltafilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionfilter',
            name='type',
            field=models.CharField(
                choices=[
                    ('CATEGORY',
                     'Category'),
                    ('DATEDELTA',
                     'Date delta')],
                max_length=30,
                verbose_name='Filter type'),
        ),
    ]
