# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20171003_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionfilter',
            options={
                'verbose_name': 'section filter',
                'verbose_name_plural': 'section filters'},
        ),
    ]
