# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-22 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20181111_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(
                choices=[
                    ('projects',
                     'Projects'),
                    ('organizations',
                     'Organizations')],
                default='projects',
                max_length=30,
                verbose_name='Section type'),
        ),
    ]
