# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-10 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20181204_2323'),
        ('catalogue', '0020_auto_20181122_1734'),
    ]

    operations = [
    ]
