# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-31 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_merge_20181210_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
