# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-27 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20181231_1116'),
        ('catalogue', '0022_auto_20190121_1733'),
    ]

    operations = [
    ]
