# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-11 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_merge_20190327_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
