# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-06 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_remove_channel_subchannels'),
        ('catalogue', '0025_auto_20190418_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightedFilter',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('highlighted',
                 models.IntegerField(
                     choices=[
                         (1,
                          'True'),
                         (0,
                          'False')],
                     default=1,
                     verbose_name='Highlighted')),
                ('channel',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='highlightedfilter_channel',
                     to='channels.Channel')),
            ],
            options={
                'abstract': False,
            },
            bases=(
                ovp.apps.channels.models.mixins.ChannelCreatorMixin,
                models.Model),
        ),
        migrations.AlterField(
            model_name='sectionfilter',
            name='type',
            field=models.CharField(
                choices=[
                    ('CATEGORY',
                     'Category'),
                    ('DATEDELTA',
                     'Date delta'),
                    ('HIGHLIGHTED',
                     'Highlighted')],
                max_length=30,
                verbose_name='Filter type'),
        ),
    ]
