# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-23 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_section_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='skip_address_filter',
            field=models.BooleanField(
                default=False,
                verbose_name='Skip addres filter'),
        ),
    ]
