# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-12 23:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_remove_channel_subchannels'),
        ('catalogue', '0028_section_skip_address_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Filter parameters')),
                ('component_type', models.CharField(blank=True, choices=[('administrative_area_level_1', 'administrative_area_level_1'), ('administrative_area_level_2', 'administrative_area_level_2'), ('county', 'county'), ('locality', 'locality'), ('sublocality', 'sublocality'), ('country', 'country')], max_length=100, null=True, verbose_name='Component type')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Component name')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressfilter_channel', to='channels.Channel')),
            ],
            options={
                'abstract': False,
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='sectionfilter',
            name='type',
            field=models.CharField(choices=[('CATEGORY', 'Category'), ('DATEDELTA', 'Date delta'), ('HIGHLIGHTED', 'Highlighted'), ('ADDRESS', 'Address')], max_length=30, verbose_name='Filter type'),
        ),
    ]
