# Generated by Django 2.2.11 on 2020-04-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20200312_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressfilter',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='addressfilter_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='catalogue_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='categoryfilter',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categoryfilter_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='datedeltafilter',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datedeltafilter_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='highlightedfilter',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='highlightedfilter_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='section',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='catalogue.Catalogue'),
        ),
        migrations.AlterField(
            model_name='section',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='sectionfilter',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sectionfilter_channel', to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='sectionfilter',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filters', to='catalogue.Section'),
        ),
    ]
