# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-28 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True),
        ),
    ]
